### PR TITLE
Improved auth support

### PR DESCRIPTION
**Pull request by nzapponi**
- Support for multi factor authentication
- Support to recover 403 rate limit errors

### CODE REVIEW

**Comment by nzapponi** [comment]
Still missing support for accessory configuration when initial login fails due to 403.

**Comment by nikonratm** [comment]
This all looks great! 

As for your TODO, what if in the `login` method of simplisafe.js (around line 175, in the else block for the 403 error) we have the function wait `this.nextBlockInterval` and then call `login` again? Then initialLoad would essentially wait until successful login, no?

**Comment by nzapponi** [comment]
That’s something I had considered (and actually implemented), but then I thought that keeping the initialLoad hanging potentially for hours might cause trouble with Homebridge, as configureAccessory and similar just wouldn’t complete. 

But you might be right... I need to test it out.

Tomorrow I’ll test it with this logic in both scenarios:
1. Rate limiting starting while the plugin is already running
2. Rate limiting already occurring before the plugin initializes

I’ll test it using a proxy to simulate 403s and report results of the test here!

**Comment by nikonratm** [comment]
Hmm, good point, Homebridge can get unhappy if one of the plugins is misbehaving (see https://github.com/nfarina/homebridge/issues/948). 

My hope is in this situation that these accessories will show "No Response" which IMHO would be a reasonable user experience as it signals "something is wrong" and presumably one would check the logs and discover rate limiting / login issue etc. But yea, if it brings down the entire Homebridge server making all other plugins unresponsive that's not ideal =)

Let us know how testing goes, and thanks as always!

**Comment by nzapponi** [comment]
As expected, things look good with rate limit management when the plugin is already running, but behavior is really odd upon first login. I'll update the logic and then test it out a bit more.

**Comment by nzapponi** [comment]
@nikonratm this should be working now! Could you help me test it by keeping it on for some time and see how it goes?

**Comment by nikonratm** [comment]
Cool! Will do. I see the new dummy accessory, seems like an interesting solution.

🙏🏼

**Comment by nzapponi** [comment]
Yeah, had to do that because if I didn't set a `get` and `set` method, Homebridge would just show the last state of the alarm instead of No Response. This way, it shows No Response, and then recovers from it when rate limiting is gone!

**Comment by nzapponi** [comment]
Merged into master! @nikonratm let's test for a couple of days before releasing on npm.

**Comment by graanco** [comment]
I am really wondering is this is happening because of the header file always match the same const clientUuid = '4df55627-46b2-4e2c-866b-1521b395ded2'; everywhere. You get multiple people using the same one to connect to their servers. Wouldn't it be better to have a different or random one?

**Comment by nzapponi** [comment]
> I am really wondering is this is happening because of the header file always match the same const clientUuid = '4df55627-46b2-4e2c-866b-1521b395ded2'; everywhere. You get multiple people using the same one to connect to their servers. Wouldn't it be better to have a different or random one?

Not really, that's required for API calls to be successful. This issue is closed so it should be resolved anyway!

**Pull request merged**
