### PR TITLE
Change setCharacteristic to updateCharacteristic

### PR DESCRIPTION
**Pull request by nikonratm**
Part of #66 #63 #56

### CODE REVIEW

**Comment by nikonratm** [comment]
@nzapponi I'm just going in circles in my brain over this, let me know if I'm off track. If we always use `updateCharacteristic` that would essentially bypass `setTargetState` in alarm.js which isnt what we want, so now I'm thinking they should be reversed, e.g. when changing the 'target' state we use `setCharacteristic` which will let the setter (`setTargetState`) handle things and for 'current' state we use `updateCharacteristic`? Again, not sure if I'm off base here... Sorry for any confusion.

**Comment by nzapponi** [comment]
Thanks for all the research on this, I’ll spend some time tomorrow investigating all the issues you raised. My understanding was that setCharacteristic updates the characteristic and calls listeners, which is required when we need to make API calls to SS etc, whereas updateCharacteristic simply updates the state of a sensor in HomeKit. 

So far I used updateCharacteristic everywhere except for where I needed to make API calls to SS. 

I’ll check what you raised and related homebridge issues and see what the best solution is. Thanks!

**Comment by nikonratm** [comment]
Yea I’ve sorta just driven myself insane with this because my system wasn't cooperating—I can’t tell if the update/setCharacteristic is a bit of a ‘red herring’ even if it’s technically correct. I do think the plugin should be exclusively using `update` since all of the plugin functions are responding to calls from SS, either via polling or API. The `setTargetState` listener is needed just for when state change comes the other direction, e.g. from HomeKit, but should be bypassed (using `updateCharacteristic`) when responding to changes coming from SS.

But yea, appreciate the objective non-insane thoughts =)

**Comment by nzapponi** [comment]
Yeah sounds like you're right. It's more of a red herring as you say, since the `setValue` function still supports using the `updateValue` logic when there are no listeners.

https://github.com/KhaosT/HAP-NodeJS/blob/bace3b682fa664993a1d5504ffed42b5c08fed4c/src/lib/Characteristic.ts#L615-L624

Reading through all the issues you mentioned elsewhere, it seems to me like it's a HomeKit hub issue rather than Homebridge... it looks as if it didn't register a listener with Homebridge.

I'll do some testing and let you know!

**Comment by nzapponi** [comment]
Merged in.

**Comment by williamw** [comment]
Leaving a response for people who might find this thread: I also ran into this issue. Try creating the automation with the Home+ app or Eve Home app, not the Apple Home app. When I created the automation using the Apple Home app, it would never fire when I armed my SimpliSafe system. However, when I created the automation using Home+, it fired immediately when the SimpliSafe system armed.

**Pull request closed without merging**
